GET <index>/_search
{
  "size": 0,
  "aggs": {
    "customers": {
      "terms": {
        "field": "<filter_field>",
        "size": 10
      },
      "aggs": {
        "dates": {
          "date_histogram": {
            "field": "@timestamp",
            "calendar_interval": "minute"
          },
          "aggs": {
            "stats": {
              "stats": {
                "field": "@timestamp"
              }
            },
            "average_delta": {
              "bucket_script": {
                "buckets_path": {
                  "count": "stats.count",
                  "max": "stats.max",
                  "min": "stats.min"
                },
                "script": "(params.max - params.min)/(params.count - 1)/1000"
              }
            }
          }
        }
      }
    }
  }
}
